### ISSUE TITLE
Post source code

### ISSUE THREAD

**Issue by krisives** [gamer9xxx/TestingRepo#1]
Currently the `.exe` and `.dll` files could contain god knows what. Please post the source code so people can verify the contents of the tool.

**Comment by gamer9xxx** [comment]
If I post the source code, people still won't be able to verify what's in the binaries.
If you are looking for how to do such thing, just google for "DirectX hooking".

The reason why I didn't post the code is that people could start using it for cheating. If someone wants to cheat, he will find his way, but this would be like serving him the cheats on a silver plate (which is strongly against the idea of the project).

Anyway, anyone with some idea can always drop me an email and I can give a private access to the code.

**Comment by krisives** [comment]
> If I post the source code, people still won't be able to verify what's in the binaries.

That's actually not true. See [reproducible builds](https://reproducible-builds.org/) for information. Even if *you* don't follow the build guidelines others can still verify the binary coverage. The basic idea is that if I have the source code I can build a binary myself then compare it to the published binary and find any areas that aren't part of the known coverage.

> If you are looking for how to do such thing, just google for "DirectX hooking".

I have no interest in developing any such tools.

> The reason why I didn't post the code is that people could start using it for cheating. If someone wants to cheat, he will find his way, but this would be like serving him the cheats on a silver plate (which is strongly against the idea of the project).

Firstly, I don't really think HOTS is a game where cheating is a problem. Second, the vast majority of the work needed to create a cheat would involve reverse engineering the data structures for the in-game logic.

> Anyway, anyone with some idea can always drop me an email and I can give a private access to the code.

That makes it difficult to safely recommend this project to others, which is the reason I created this bug. From time to time people show up in `/r/heroesofthestorm` and mention they have a system too weak to play the game and I enjoy posting them a link to this tool, but I would really prefer to be able to do so without worrying about exposing them to a security problem.
